Value space consumption optimization
elliotchance/reflect pull request #7
Opened 2021-08-03 19:36 UTC by Terisback

2021-08-03 20:02 UTC, elliotchance requested changes

2021-08-03 20:02 UTC, elliotchance commented on value.v
> +			// .is_f64 { voidptr(&v2.value_f64) }
nit: Can you remove these now?

2021-08-04 02:54 UTC, Terisback commented on value.v
> +			// .is_f64 { voidptr(&v2.value_f64) }
Yep

2021-08-04 03:15 UTC, Terisback commented
Last commit uses union compare, rn can't check what code it generates, and tests not so representable because of only one type [tested](https://github.com/Terisback/reflect/blob/57bf85757fda9d7213d7bfc595af236353b757f8/value_test.v#L204)
It needs investigation, does it work right or not

2021-08-04 03:50 UTC, elliotchance approved these changes

2021-08-04 03:51 UTC, merged